---

- name: Create user
  user:
    state: present
    name: "{{ current_user.name }}"
    uid: "{{ um_uid_base + current_user.rel_uid }}"
    password: "{{ current_user.passwd | default(omit) }}"
    groups: "{{ current_user.groups | default(omit) }}"
    system: false

- name: Configure user's authorized keys
  authorized_key:
    user: "{{ current_user.name }}"
    key: "{{ item }}"
  loop: "{{ [current_user.authorized_keys | default([])] | flatten}}"
  when: not ansible_check_mode
