---

- name: Group should exist
  when:
    - ((group_names + ['all']) | intersect(current_group.present | default(['all']))) | length > 0
    - ((group_names + ['all']) | intersect(current_group.absent | default([]))) | length == 0
  block:
    - name: Create group
      group:
        state: present
        name: "{{ current_group.name }}"
        gid: "{{ um_gid_base + current_group.rel_gid }}"
        system: no

    - name: Create sudoer file associated with this group
      when: current_group.sudoer is defined
      copy:
        dest: "/etc/sudoers.d/rel_gid_{{ current_group.rel_gid }}"
        mode: 0440
        content: "{{ current_group.sudoer }}"


- name: Group should not exist
  when: ((group_names + ['all']) | intersect(current_group.present | default(['all']))) | length <= 0 or
        ((group_names + ['all']) | intersect(current_group.absent | default([]))) | length > 0
  block:
    - name: Remove group
      group:
        state: absent
        name: "{{ current_group.name }}"

    - name: Remove sudoer file associated with this group
      file:
        state: absent
        path: "/etc/sudoers.d/rel_gid_{{ current_group.rel_gid }}"
