---

- name: Create or remove current user
  user:
    state: "{{ current_user.active | default(true) }}"  # TODO: this should also consider 'absent'. Revise 'when' condition in outer loop.
    name: "{{ current_user.name }}"
    uid: "{{ um_uid_base + current_user.rel_uid }}"
    password: "{{ current_user.passwd | default(omit) }}"
    groups: "{{ current_user.groups | default(omit) }}"  # TODO: make sure the groups exist (intersect?)

- name: Configure user's authorized_keys
  authorized_key:
    user: "{{ current_user.name }}"
    key: "{{ item }}"
    exclusive: true
  loop: "{{ [current_user.authorized_keys | default([])] | flatten}}"
  when: "{{ current_user.active | default(true) }}"
