---

- name: Create or remove current user
  user:
    state: "{{ current_user.active | default(true) }}"
    name: "{{ current_user.name }}"
    uid: "{{ uid_base + current_user.rel_uid }}"
    password: "{{ current_user.passwd | default(omit) }}"

- name: Configure user's authorized_keys
  authorized_key:
    user: "{{ current_user.name }}"
    key: "{{ item }}"
    exclusive: true
  loop: "{{ current_user.authorized_keys | default([]) }}"
  when: "{{ current_user.active | default(true) }}"
