---

- name: Remove group
  group:
    state: absent
    name: "{{ current_group.name }}"

- name: Remove sudoer file associated with this group
  file:
    state: absent
    path: "/etc/sudoers.d/rel_gid_{{ current_group.rel_gid }}"
