---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - check
    - destroy
platforms:
  - name: centos6
    image: geerlingguy/docker-centos6-ansible
    pre_build_image: true
    pull: true
    privileged: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
    pull: true
    privileged: true
  - name: ubuntu
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
    pull: true
    privileged: true
  - name: fedora
    image: geerlingguy/docker-fedora29-ansible
    pre_build_image: true
    pull: true
    privileged: true
driver:
  name: docker
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
