---
name: Molecule Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4

    env:
      ANSIBLE_FORCE_COLOR: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule docker molecule-docker pytest pytest-testinfra
      - name: Show versions
        run: |
          python --version
          docker --version
          ansible --version
      - name: Test with molecule
        run: |
          molecule test --all
